FROM maven:3.8.5-openjdk-17 AS build
COPY . . 
RUN mvn clean package -DskipTests

FROM openjdk:17.01-jdk-slim
COPY --from=build /target/coffeebean-0.0.1-SNAPSHOT.jar  coffeebean.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","coffeebean.jar"]